# FROM golang:latest

# LABEL maintainer="Mainul Hasan"

# WORKDIR /app

# COPY go.mod .

# COPY go.sum .

# RUN go mod download

# COPY . .

# ENV PORT 8000

# RUN go build

# CMD["/.Go-Rest-Api-Postgres-Booklist-Project"]